version: "3"

services:
  dashboard:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./src:/app/src
    ports:
      - "${APP_PORT:-80}:3000"
    networks:
      - app_network

networks:
    app_network:
        driver: bridge
        external: true